layout_spectrum: 0.3933932
typography_spectrum: 0.2012855
color:
  saturation: 0.6205373
  lightness: 0.1798169
  brandStrength: 0.5642138
  rhythmicContrast: 0.4791745
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Pakistan
